# Generated by Django 3.2.5 on 2021-10-24 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('itching', models.BooleanField()),
                ('skin_rash', models.BooleanField()),
                ('vomiting', models.BooleanField()),
                ('fatigue', models.BooleanField()),
                ('weight_loss', models.BooleanField()),
                ('irregular_sugar_level', models.BooleanField()),
                ('sunken_eyes', models.BooleanField()),
                ('dehydration', models.BooleanField()),
                ('indigestion', models.BooleanField()),
                ('yellowish_skin', models.BooleanField()),
                ('nausea', models.BooleanField()),
                ('loss_of_appetite', models.BooleanField()),
                ('abdominal_pain', models.BooleanField()),
                ('diarrhoea', models.BooleanField()),
                ('yellowing_of_eyes', models.BooleanField()),
                ('blurred_and_distorted_vision', models.BooleanField()),
                ('obesity', models.BooleanField()),
                ('excessive_hunger', models.BooleanField()),
                ('passage_of_gases', models.BooleanField()),
                ('internal_itching', models.BooleanField()),
                ('dischromic_patches', models.BooleanField()),
                ('increased_appetite', models.BooleanField()),
                ('polyuria', models.BooleanField()),
                ('prognosis', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
