# Generated by Django 3.2.5 on 2021-10-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211025_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='abdominal_pain',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='blurred_and_distorted_vision',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='dehydration',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='diarrhoea',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='dischromic_patches',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='excessive_hunger',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='fatigue',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='increased_appetite',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='indigestion',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='internal_itching',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='irregular_sugar_level',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='itching',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='loss_of_appetite',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='nausea',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='obesity',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='passage_of_gases',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='polyuria',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='skin_rash',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='sunken_eyes',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='vomiting',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='weight_loss',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='yellowing_of_eyes',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='yellowish_skin',
            field=models.CharField(choices=[('', 'Select Gender'), ('Present', 'Yes'), ('Absent', 'No')], max_length=20),
        ),
    ]
